loglevel = "DEBUG"

[backends]
	##Drops 
		[backends.drops]
			[backends.drops.servers.servers1]
			path = "/"
			url = "http://172.2.0.3:9000"

[frontends]
	[frontends.drops]
		backend = "drops"
		entrypoints = ["http"]
		[frontends.drops.headers.customresponseheaders]
		X-Custom-Response-Header = "True"
		X-Forwarded-Prefix = "True"
		[frontends.drops.headers.customrequestheaders]
		X-Script-Name = "drops"
		[frontends.drops.routes.drops_1]
		rule = "Host:drops.vca.informatik.hu-berlin.de;PathPrefixStrip:/"
