loglevel = "DEBUG"

[backends]
	##Drops 
		[backends.drops]
			[backends.drops.servers.servers1]
			url = "http://drops.docker.local:9000"

[frontends]
	[frontends.drops]
		backend = "drops"
		entrypoints = ["http"]
		[frontends.drops.routes.drops_1]
		rule = "Host:vca.informatik.hu-berlin.de; Path:/"
